apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/serviceaccount.yaml
- manifests/rolebinding.yaml
- manifests/cronjob.yaml
