---
collections:
  - name: community.general
    version: 3.9.0
  - name: kubernetes.core
    version: 1.2.3
roles:
  - name: my_custom_role
    version: 1.0.0
    src: https://github.com/username/my_custom_role
