
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config-map
  namespace: default
data:
  config.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: null
    receivers: []
    

