
# secrets.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
  namespace: default
data:
  secret-key: test

# configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  config-key: data

# deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: my-secrets
        - configMapRef:
            name: my-configmap

# service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

# route.yaml
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-app-route
  namespace: default
spec:
  to:
    kind: Service
    name: my-app-service
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
