apiVersion: v1
kind: Pod
metadata:
  name: app2
  namespace: default
  labels:
    app: app2
annotations:
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 1m
        memory: 128Mi
      limits:
        cpu: 2m
        memory: 256Mi
