configmap name : website-configmap
data:
  environment: Production
  version: v1.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: website-configmap
namespace: myapp 
data:
  environment: Production
  version: v1.0
