name: Deploy Kubernetes Cluster to GitHub Codespace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub Codespace
        uses: actions/github-script@5.0.0
        with:
          script: |
            gh codespace create --name "My Codespace"
            gh codespace wait --name "My Codespace"
            gh codespace enable-feature --name "My Codespace" --extension "ms-python.vscode-pylance"

      - name: Install dependencies
        run: |
          pip install ansible

      - name: Run Ansible playbook
        run: |
          ansible-galaxy install -r requirements.yml
          ansible-playbook playbook.yaml -e @input.yml
